name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Test (Node.js 20.x, Ubuntu)"
            os: ubuntu-latest
            node-version: "20.x"
          - name: "Test (Node.js 22.x, Ubuntu)"
            os: ubuntu-latest
            node-version: "22.x"
          - name: "Test (Node.js 24.x, Ubuntu)"
            os: ubuntu-latest
            node-version: "24.x"
          - name: "Lint"
            os: ubuntu-latest
            node-version: "20.x"
          - name: "Build & Package"
            os: ubuntu-latest
            node-version: "20.x"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      run: npm test
      
    - name: Run linting
      if: matrix.name == 'Lint'
      run: npm run lint

    - name: Build and package
      if: matrix.name == 'Build & Package'
      run: |
        npm pack --dry-run
        echo "Package size:"
        npm pack --silent | xargs ls -lh
        
    - name: Test CLI installation
      if: matrix.name == 'Build & Package'
      run: |
        npm pack
        npm install -g *.tgz
        flame --help
        
