name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Test (Node.js 18.x, Ubuntu)"
            os: ubuntu-latest
            node-version: "18.x"
            task: "test"
          - name: "Test (Node.js 20.x, Ubuntu)"
            os: ubuntu-latest
            node-version: "20.x"
            task: "test"
            coverage: true
          - name: "Test (Node.js 22.x, Ubuntu)"
            os: ubuntu-latest
            node-version: "22.x"
            task: "test"
          - name: "Test (Node.js 24.x, Ubuntu)"
            os: ubuntu-latest
            node-version: "24.x"
            task: "test"
          - name: "Test (Node.js 20.x, Windows)"
            os: windows-latest
            node-version: "20.x"
            task: "test"
          - name: "Test (Node.js 22.x, Windows)"
            os: windows-latest
            node-version: "22.x"
            task: "test"
          - name: "Lint"
            os: ubuntu-latest
            node-version: "20.x"
            task: "lint"
          - name: "Build & Package"
            os: ubuntu-latest
            node-version: "20.x"
            task: "build"
          - name: "Integration Tests"
            os: ubuntu-latest
            node-version: "20.x"
            task: "integration"
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: false
        
    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      if: matrix.task == 'test'
      run: npm test
      
    - name: Upload coverage reports
      if: matrix.coverage
      uses: codecov/codecov-action@v3
      continue-on-error: true
      
    - name: Run linting
      if: matrix.task == 'lint'
      run: npm run lint

    - name: Build and package
      if: matrix.task == 'build'
      run: |
        npm pack --dry-run
        echo "Package size:"
        npm pack --silent | xargs ls -lh
        
    - name: Test CLI installation
      if: matrix.task == 'build'
      run: |
        npm pack
        npm install -g *.tgz
        flame --help
        
    - name: Upload package artifact
      if: matrix.task == 'build'
      uses: actions/upload-artifact@v4
      with:
        name: npm-package
        path: '*.tgz'
        retention-days: 7
      
    - name: Run integration tests
      if: matrix.task == 'integration'
      run: npm run test -- test/integration.test.js
      
    - name: Test examples
      if: matrix.task == 'integration'
      run: |
        timeout 30s node examples/load-test-server.js &
        SERVER_PID=$!
        sleep 5
        node examples/run-load-test.js
        kill $SERVER_PID || true